package games

import (
	_ "embed"
	"strings"
	"sync"
)

// CMU Pronouncing Dictionary with the CEFR level attached where we know it.
// Format: "word<TAB>ARPAbet<TAB>CEFR or empty<TAB>comma-separated target sounds".
// Generated by scripts/gen_pronunciation_dict.py from cmudict + cefr.tsv.
//
// The file carries two jobs that are easy to confuse:
//
//   - Membership answers "can we trust the reference pronunciation?". A word
//     that is absent has no human-written transcription, so the correct
//     pronunciation would have to be guessed by a g2p model. A wrong guess
//     marks correct speech as an error, which is the largest source of false
//     feedback in mispronunciation detection - so absent means reject.
//
//   - The CEFR column answers "is this passage really at the level it claims?".
//     Only ~8k of the 125k words carry a level; inflected forms and
//     contractions ("walked", "don't") are legitimate but ungraded, so they
//     are skipped by the level check rather than failing it.
//
//go:embed assets/pronunciation_dict.tsv
var pronDictRaw string

// PronEntry is one dictionary row.
type PronEntry struct {
	Phonemes string   // ARPAbet with stress digits, e.g. "TH IH1 NG K"
	Level    string   // A1..C2, or "" when the word is not CEFR-graded
	Sounds   []string // target sounds this word exercises; may be empty
}

var (
	pronOnce sync.Once
	pronDict map[string]PronEntry
)

func loadPronDict() {
	pronDict = make(map[string]PronEntry, 128000)
	for _, line := range strings.Split(pronDictRaw, "\n") {
		if line == "" || line[0] == '#' {
			continue
		}
		f := strings.Split(line, "\t")
		if len(f) < 4 || f[0] == "" {
			continue
		}
		var sounds []string
		if f[3] != "" {
			sounds = strings.Split(f[3], ",")
		}
		pronDict[f[0]] = PronEntry{Phonemes: f[1], Level: f[2], Sounds: sounds}
	}
}

// PronLookup returns the dictionary entry for a word, lowercased by the caller
// or not - lookup is case-insensitive.
func PronLookup(word string) (PronEntry, bool) {
	pronOnce.Do(loadPronDict)
	e, ok := pronDict[strings.ToLower(word)]
	return e, ok
}

// PronDictSize reports how many words are loaded. Used by the boot log so a
// truncated or missing asset is visible immediately rather than showing up
// later as every passage being rejected.
func PronDictSize() int {
	pronOnce.Do(loadPronDict)
	return len(pronDict)
}

// PronTokens splits a passage into comparable word tokens: lowercased, outer
// punctuation removed, inner apostrophes kept so "don't" stays one word.
// Hyphenated forms are split, because CMUdict stores the parts separately.
func PronTokens(text string) []string {
	var out []string
	for _, raw := range strings.FieldsFunc(strings.ToLower(text), func(r rune) bool {
		return r == ' ' || r == '\t' || r == '\n' || r == '-' || r == '—'
	}) {
		w := strings.Trim(raw, ".,!?;:\"'()[]…“”‘’")
		// A leading apostrophe is punctuation; an inner one is part of the word.
		if w != "" {
			out = append(out, w)
		}
	}
	return out
}

// PronAnalyse walks a passage and returns its phoneme string, the set of target
// sounds it exercises, and any words missing from the dictionary.
//
// A non-empty unknown list means the passage must be rejected: that is the
// guarantee that makes the learner's feedback trustworthy. Phonemes are
// returned so they can be stored once at insert time, keeping g2p off the
// request path entirely.
func PronAnalyse(text string) (phonemes string, sounds []string, unknown []string) {
	pronOnce.Do(loadPronDict)

	var ph []string
	seen := map[string]struct{}{}
	for _, w := range PronTokens(text) {
		e, ok := pronDict[w]
		if !ok {
			unknown = append(unknown, w)
			continue
		}
		ph = append(ph, e.Phonemes)
		for _, s := range e.Sounds {
			if _, dup := seen[s]; !dup {
				seen[s] = struct{}{}
				sounds = append(sounds, s)
			}
		}
	}
	return strings.Join(ph, " "), sounds, unknown
}

// Minimum share of a passage's words that must carry a CEFR level before we are
// willing to judge its level at all, and the minimum number of such words.
//
// Without this, the check is trivially fooled: "The unprecedented deterioration
// jeopardised subsequent negotiations" has exactly one graded word ("the", A1),
// so measuring only graded words scores it 100% A1. The hard vocabulary is
// invisible precisely because it is too advanced to be in a graded list. So an
// unverifiable passage is rejected rather than assumed easy.
const (
	pronMinGradedCoverage = 0.60
	pronMinGradedWords    = 4
)

// PronLevelFits reports whether a passage really sits at the claimed CEFR
// level. It returns the share of graded words at or below that level, and what
// fraction of the passage carried a level at all.
//
// This exists because LLMs routinely ignore a CEFR instruction in the prompt -
// they will happily label a C1 sentence "A2". Rather than trust the label, we
// measure it against the graded vocabulary we already ship.
func PronLevelFits(text, level string, minShare float64) (ok bool, share, coverage float64) {
	pronOnce.Do(loadPronDict)

	rank := map[string]int{"A1": 1, "A2": 2, "B1": 3, "B2": 4, "C1": 5, "C2": 6}
	want, known := rank[strings.ToUpper(level)]
	if !known {
		return false, 0, 0
	}

	tokens := PronTokens(text)
	if len(tokens) == 0 {
		return false, 0, 0
	}

	graded, within := 0, 0
	for _, w := range tokens {
		e, found := pronDict[w]
		if !found || e.Level == "" {
			continue
		}
		graded++
		if rank[e.Level] <= want {
			within++
		}
	}

	coverage = float64(graded) / float64(len(tokens))
	if graded < pronMinGradedWords || coverage < pronMinGradedCoverage {
		// Too little graded vocabulary to judge - do not claim a level.
		return false, 0, coverage
	}
	share = float64(within) / float64(graded)
	return share >= minShare, share, coverage
}
