package services

import (
	"errors"
	"fmt"
	"image"
	"image/jpeg"
	"image/png"
	"io"
	"mime/multipart"
	"os"
	"path/filepath"

	"github.com/google/uuid"
	"github.com/rs/zerolog/log"
	"github.com/speak-up/backend/internal/config"
	"github.com/speak-up/backend/internal/database"
	"github.com/speak-up/backend/internal/models"
)

// Centre logo storage.
//
// This is the first and only place the backend writes a user-supplied
// file to disk, so the rules are strict:
//
//  1. SIZE is capped before anything is read into memory.
//  2. The bytes are DECODED as an image, not trusted by extension. A
//     .png that isn't a PNG is refused here rather than being served
//     back to browsers later.
//  3. The image is RE-ENCODED from the decoded pixels. This is the key
//     step: the file we store is generated by us, so no EXIF payload,
//     no polyglot file, no trailing appended data survives.
//  4. The FILENAME is derived from the centre's UUID, never from the
//     upload. Path traversal is impossible because no user-controlled
//     string reaches the path.
//  5. Only PNG and JPEG are accepted - both are in the standard library,
//     so supporting them costs no dependency and no decoder surface we
//     haven't already got.

const (
	// maxLogoBytes - 2 MB is generous for a logo and small enough that a
	// flood of uploads can't fill the disk.
	maxLogoBytes = 2 << 20

	// maxLogoDimension guards against a decompression bomb: a tiny PNG
	// can declare enormous dimensions and blow up memory on decode.
	maxLogoDimension = 4000
)

// ErrBadLogo's text is user-facing: rejections are wrapped with %w and
// the full string is returned to the centre, so it reads as one Uzbek
// sentence ("logotip qabul qilinmadi: rasm hajmi...").
var ErrBadLogo = errors.New("logotip qabul qilinmadi")

// LogoDir returns the directory logos live in, creating it on demand.
func LogoDir() string {
	return filepath.Join(config.App.UploadDir, "centers")
}

// SaveCenterLogo validates, re-encodes and stores an uploaded logo, then
// points the centre at it and sends the profile back for review.
//
// Returns the public path (e.g. "/uploads/centers/<uuid>.png").
func SaveCenterLogo(centerID uuid.UUID, fh *multipart.FileHeader) (string, error) {
	if fh == nil {
		return "", ErrBadLogo
	}
	if fh.Size <= 0 || fh.Size > maxLogoBytes {
		return "", fmt.Errorf("%w: rasm hajmi 2 MB dan oshmasligi kerak", ErrBadLogo)
	}

	src, err := fh.Open()
	if err != nil {
		return "", ErrBadLogo
	}
	defer src.Close()

	// Read the HEADER ONLY first. This is the decompression-bomb guard:
	// a 40 KB PNG can legally declare 50000x50000 pixels, which would be
	// ~10 GB once decoded. DecodeConfig parses just the dimensions, so we
	// can refuse it before allocating anything.
	cfg, format, err := image.DecodeConfig(src)
	if err != nil {
		return "", fmt.Errorf("%w: fayl rasm emas (faqat PNG yoki JPEG)", ErrBadLogo)
	}
	if format != "png" && format != "jpeg" {
		return "", fmt.Errorf("%w: faqat PNG yoki JPEG qabul qilinadi", ErrBadLogo)
	}
	if cfg.Width <= 0 || cfg.Height <= 0 ||
		cfg.Width > maxLogoDimension || cfg.Height > maxLogoDimension {
		return "", fmt.Errorf("%w: rasm o'lchami 4000px dan oshmasligi kerak", ErrBadLogo)
	}

	// Header checks passed - rewind and decode for real.
	if _, err := src.Seek(0, io.SeekStart); err != nil {
		return "", ErrBadLogo
	}
	img, _, err := image.Decode(src)
	if err != nil {
		return "", fmt.Errorf("%w: fayl rasm emas (faqat PNG yoki JPEG)", ErrBadLogo)
	}

	dir := LogoDir()
	if err := os.MkdirAll(dir, 0o755); err != nil {
		log.Error().Err(err).Str("dir", dir).Msg("SaveCenterLogo: mkdir failed")
		return "", err
	}

	ext := "png"
	if format == "jpeg" {
		ext = "jpg"
	}
	filename := centerID.String() + "." + ext
	fullPath := filepath.Join(dir, filename)

	// Write to a temp file in the same directory, then rename. A crash
	// mid-write can never leave a half-decoded logo being served.
	tmp, err := os.CreateTemp(dir, ".upload-*")
	if err != nil {
		return "", err
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName) // no-op once the rename succeeds

	// Re-encode from decoded pixels - this is what strips anything the
	// original file was carrying.
	if format == "png" {
		err = png.Encode(tmp, img)
	} else {
		err = jpeg.Encode(tmp, img, &jpeg.Options{Quality: 88})
	}
	if cerr := tmp.Close(); err == nil {
		err = cerr
	}
	if err != nil {
		return "", err
	}

	if err := os.Chmod(tmpName, 0o644); err != nil {
		return "", err
	}
	if err := os.Rename(tmpName, fullPath); err != nil {
		return "", err
	}

	// A centre that previously uploaded the other format would otherwise
	// leave an orphan behind, and the stale file would still be served.
	otherExt := "jpg"
	if ext == "jpg" {
		otherExt = "png"
	}
	os.Remove(filepath.Join(dir, centerID.String()+"."+otherExt))

	publicPath := "/uploads/centers/" + filename
	if err := database.DB.Model(&models.StudyCenter{}).
		Where("id = ?", centerID).
		Update("logo_url", publicPath).Error; err != nil {
		return "", err
	}

	// New artwork is new public content: back through review it goes.
	MarkCenterPending(centerID)

	log.Info().
		Str("center_id", centerID.String()).
		Str("format", format).
		Int64("bytes", fh.Size).
		Msg("Center logo uploaded")

	return publicPath, nil
}
